#!/usr/bin/env python3
"""
capture_runtime_baseline.py — Runtime State Baseline Capture Tool

Run this script after `docker compose up` from a known-good state.
It inspects each workload node container and writes the current runtime
configuration to risk_engine/config/runtime_baseline.yaml.

Usage:
    python3 scripts/capture_runtime_baseline.py [--nodes node1,node2,node3,node4]
    python3 scripts/capture_runtime_baseline.py --out ./risk_engine/config/runtime_baseline.yaml

Only run this from a verified clean state. The output becomes the security
baseline — any subsequent drift from it will raise RUNTIME_DRIFT alerts.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import docker
import yaml

DEFAULT_NODES   = ["node1", "node2", "node3", "node4"]
DEFAULT_OUT     = "./risk_engine/config/runtime_baseline.yaml"

HEADER = """\
# Runtime baseline for workload containers.
# Generated by scripts/capture_runtime_baseline.py from a known-good state.
# DO NOT edit manually — regenerate after any intentional compose change.
#
# Regenerate with:
#   python3 scripts/capture_runtime_baseline.py
"""


def extract_state(container) -> dict:
    container.reload()
    attrs    = container.attrs
    hc       = attrs.get("HostConfig", {})
    cfg      = attrs.get("Config", {})
    nets     = sorted(attrs.get("NetworkSettings", {}).get("Networks", {}).keys())
    rp       = hc.get("RestartPolicy", {})
    return {
        "user":           cfg.get("User", ""),
        "cap_add":        sorted(hc.get("CapAdd") or []),
        "binds":          sorted(hc.get("Binds") or []),
        "networks":       nets,
        "restart_policy": f"{rp.get('Name','no')}:{rp.get('MaximumRetryCount',0)}",
        "security_opts":  sorted(hc.get("SecurityOpt") or []),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Capture runtime baseline for workload nodes.")
    parser.add_argument("--nodes", default=",".join(DEFAULT_NODES),
                        help="Comma-separated container names")
    parser.add_argument("--out",   default=DEFAULT_OUT,
                        help="Output YAML path")
    args = parser.parse_args()

    nodes = [n.strip() for n in args.nodes.split(",") if n.strip()]

    try:
        client = docker.from_env()
    except Exception as e:
        print(f"[ERROR] Cannot connect to Docker daemon: {e}", file=sys.stderr)
        return 1

    baseline: dict[str, dict] = {}
    for node in nodes:
        try:
            container = client.containers.get(node)
            if container.status != "running":
                print(f"  [SKIP] {node} is not running (status={container.status})")
                continue
            state = extract_state(container)
            baseline[node] = state
            print(f"  [OK]   {node}: user={state['user']!r} nets={state['networks']}")
        except docker.errors.NotFound:
            print(f"  [SKIP] {node}: container not found")
        except Exception as e:
            print(f"  [WARN] {node}: {e}")

    if not baseline:
        print("[ERROR] No nodes captured. Is docker compose up?", file=sys.stderr)
        return 1

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with open(out_path, "w") as f:
        f.write(HEADER + "\n")
        yaml.dump({"baseline": baseline}, f, default_flow_style=False, sort_keys=True)

    print(f"\nBaseline written to: {out_path} ({len(baseline)} node(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
