#!/usr/bin/env python3
"""
capture_approved_images.py — Image Digest Baseline Capture Tool

Run after `docker compose build` from a known-good, verified state.
Writes image digests for each workload container to approved_images.yaml.

Usage:
    python3 scripts/capture_approved_images.py
    python3 scripts/capture_approved_images.py --nodes node1,node2 --out ./risk_engine/config/approved_images.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import docker
import yaml

DEFAULT_NODES = ["node1", "node2", "node3", "node4"]
DEFAULT_OUT   = "./risk_engine/config/approved_images.yaml"

HEADER = """\
# Approved container image digests for workload nodes.
# Generated by scripts/capture_approved_images.py from a known-good build.
# DO NOT edit manually — regenerate after each intentional image rebuild.
#
# Regenerate with:
#   python3 scripts/capture_approved_images.py
"""


def get_image_digest(container) -> str:
    container.reload()
    image_id = container.attrs.get("Image", "")
    try:
        img          = container.client.images.get(image_id)
        repo_digests = img.attrs.get("RepoDigests", [])
        if repo_digests:
            return repo_digests[0]
    except Exception:
        pass
    return image_id  # Fall back to image ID (sha256:...)


def main() -> int:
    parser = argparse.ArgumentParser(description="Capture approved image digests.")
    parser.add_argument("--nodes", default=",".join(DEFAULT_NODES))
    parser.add_argument("--out",   default=DEFAULT_OUT)
    args = parser.parse_args()

    nodes = [n.strip() for n in args.nodes.split(",") if n.strip()]

    try:
        client = docker.from_env()
    except Exception as e:
        print(f"[ERROR] Cannot connect to Docker daemon: {e}", file=sys.stderr)
        return 1

    approved: dict[str, str] = {}
    for node in nodes:
        try:
            container = client.containers.get(node)
            digest    = get_image_digest(container)
            approved[node] = digest
            print(f"  [OK] {node}: {digest[:40]}...")
        except docker.errors.NotFound:
            print(f"  [SKIP] {node}: container not found")
        except Exception as e:
            print(f"  [WARN] {node}: {e}")

    if not approved:
        print("[ERROR] No images captured.", file=sys.stderr)
        return 1

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(HEADER + "\n")
        yaml.dump({"approved_images": approved}, f, default_flow_style=False, sort_keys=True)

    print(f"\nApproved images written to: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
